Repository Summer-Bootcamp-2024/SML-Backend, pull requests merged in 2024-07, with the labels that each got.

#3 Feat/request friend
  backend/api/api.py
  backend/api/endpoints/friends.py
  backend/crud/friend_crud.py
  backend/models/friends.py
  backend/schemas/friend/friends_request.py
  backend/schemas/friend/friends_schema.py
Labels: 기능구현

#6 Feat: 일촌 및 이촌 리스트 출력 API
  backend/api/api.py
  backend/api/endpoints/relationships.py
  backend/crud/relation_crud.py
  backend/schemas/friend/friends_related.py
Labels: 기능구현

#7 Feat/get pending friend
  backend/api/endpoints/friends.py
  backend/crud/friend_crud.py
  backend/schemas/friend/friends_pending.py
Labels: 기능구현

#11 Refactor/request friend
  backend/api/endpoints/friends.py
  backend/crud/friend_crud.py
  backend/schemas/friend/friends_request.py
Labels: 기능구현

#13 [#12] 일촌 요청 조회 API 엔드포인트 수정
  backend/api/endpoints/friends.py
  backend/crud/friend_crud.py
Labels: 기능구현

#15 Feat: 채팅방 생성 및 조회 API
  backend/api/api.py
  backend/api/endpoints/chatrooms.py
  backend/crud/chatroom_crud.py
  backend/models/chatrooms.py
  backend/schemas/chat/chatroom_create.py
Labels: 기능구현

#16 Feat/accept friend
  backend/api/endpoints/friends.py
  backend/api/endpoints/relationships.py
  backend/crud/friend_crud.py
  backend/crud/relation_crud.py
  backend/schemas/friend/request/friends_accept.py
  backend/schemas/friend/request/friends_request.py
  backend/schemas/friend/response/friends_pending.py
  backend/schemas/friend/response/friends_related.py
Labels: 기능구현

#21 Feat/list friend
  backend/api/endpoints/friends.py
  backend/crud/friend_crud.py
  backend/crud/user_crud.py
Labels: 기능구현

#23 Feat/delete friend
  backend/api/endpoints/friends.py
  backend/crud/friend_crud.py
Labels: 기능구현

#24 Refactor: 관계도 조회 수정
  backend/crud/relation_crud.py
Labels: 기능구현

#26 [#25]HOTFIX: 미들웨어 설정
  backend/main.py
Labels: 버그수정

#28 [#25]HOTFIX: origin 주소 변경
  backend/main.py
Labels: 버그수정

#29 [#27]Feat:일촌,이촌 검색 구현
  backend/api/endpoints/search.py
  backend/crud/search_crud.py
  backend/schemas/search/search_schema.py
  backend/utils/db_utils.py
  backend/utils/es_setup.py
  backend/utils/index_user.py
Labels: 기능구현

#33 [#32] Refactor: 로그인 기능 수정
  backend/api/endpoints/auth.py
Labels: 버그수정

#46 Feature: 채팅 기능 구현
  backend/api/api.py
  backend/api/endpoints/messages.py
  backend/crud/message_crud.py
  backend/main.py
  backend/models/chatrooms.py
  backend/models/messages.py
  backend/schemas/chat/messages.py
  backend/templates/index.html
  backend/utils/chat.py
  requirements.txt
Labels: 기능구현

#50 [#48] Refactor: 채팅방 기능 수정
  backend/api/endpoints/chatrooms.py
  backend/api/endpoints/messages.py
  backend/crud/chatroom_crud.py
  backend/schemas/chat/chatroom_create.py
Labels: 버그수정

#56 [#55] Refactor: 로그인 상태 변경 오류 수정
  backend/api/endpoints/auth.py
Labels: 버그수정

#58 [#57] Refactor: 로그인 재수정
  backend/api/endpoints/auth.py
  backend/database.py
Labels: 버그수정

#67 [#65] Refactor: 일촌 삭제 기능 수정
  backend/crud/friend_crud.py
Labels: 리팩토링

#69 [#68] Refactor: 일촌 수락/거절 기능 수정
  backend/crud/friend_crud.py
Labels: 리팩토링

#72 [#71] Refactor: 소개요청 코드수정
  backend/api/api.py
  backend/api/endpoints/introduction_request.py
  backend/crud/introduction_request_crud.py
  backend/main.py
  backend/models/chatrooms.py
  backend/models/messages.py
Labels: 리팩토링

#74 [#73] Refactor: 채팅메시지 출력 방식 변경
  backend/main.py
  backend/utils/chat.py
Labels: 리팩토링

#78 [#76] Feature: 채팅방 삭제 기능 구현
  backend/crud/friend_crud.py
  backend/templates/index.html
Labels: 기능구현

#82 [#79] Refactor: 시간형식 수정
  backend/crud/chatroom_crud.py
  backend/models/chatrooms.py
  backend/models/messages.py
  backend/schemas/chat/chatroom_create.py
  backend/schemas/chat/messages.py
  backend/schemas/credit/credit_update.py
  backend/schemas/gift/response/gift_response.py
  backend/schemas/introduction/introduction_request.py
  backend/schemas/user/user_schema.py
Labels: 리팩토링

#84 [#83] Feature: 채팅방 삭제 api구현
  backend/api/endpoints/chatrooms.py
  backend/crud/chatroom_crud.py
  backend/crud/user_crud.py
  backend/schemas/chat/chatroom_create.py
Labels: 기능구현

#86 [#85] Refactor: 채팅 메시지 수정
  backend/main.py
Labels: 리팩토링

#88 [#87] Bug: sender_id 통일
  backend/main.py
Labels: 버그수정

#90 Feat/#89 S3 연동
  backend/utils/s3_util.py
  requirements.txt
Labels: 기능구현

#92 Feat/#91 사용자 프로필 이미지 업데이트 API 구현
  backend/api/endpoints/users.py
  backend/crud/user_crud.py
  backend/models/user.py
  backend/schemas/user/user_schema.py
  backend/schemas/user/user_update.py
  backend/utils/s3_util.py
Labels: 기능구현

#98 [#97] Chore: Dockerfile 수정
  Dockerfile
Labels: 기타/환경설정

#100 [#99] Feat: 프로메테우스, 그라파나
  .gitignore
  backend/main.py
  requirements.txt
Labels: 기능구현

#108 [#107] Refactor: 소개요청 endpoint 수정
  backend/api/endpoints/introduction_request.py
Labels: 리팩토링

#120 [#119] Refactor: 회원가입 request body 수정
  backend/crud/user_crud.py
  backend/models/user.py
  backend/schemas/search/search_schema.py
  backend/schemas/user/user_create.py
  backend/schemas/user/user_schema.py
Labels: 리팩토링

#122 [#121] Refactor: origins 주소 수정
  backend/main.py
Labels: 리팩토링

#132 [#131] test 폴더 구조 생성
  test/api/__init__.py
  test/crud/__init__.py
  test/schemas/__init__.py
Labels: 기타/환경설정

#136 [#135] Bug: 선물하기 api 외래키 문제 버그 수정
  models/credit_transaction.py
Labels: 버그수정

#138 Hotfix/#137
  main.py
  utils/__init__.py
  utils/s3_util.py
Labels: 버그수정
